import{useEffect,useState}from'react';
import{Cloud,FileUp,KeyRound,LoaderCircle,RefreshCw,X}from'lucide-react';
import type{AiConfig,AiProvider}from'./types';
import{defaultProfile,depthOptions,strictnessOptions,templates,type AnalysisProfile,type ProviderProfile}from'./analysisProfile';

const providerNames:{id:AiProvider;label:string;hint:string}[]=[
 {id:'azure',label:'Azure OpenAI',hint:'Azure-Endpunkt mit Deployment gpt-5-mini'},
 {id:'openai',label:'OpenAI API',hint:'Verfügbare Textmodelle aus dem OpenAI-Konto'},
 {id:'anthropic',label:'Claude (Anthropic)',hint:'Claude-Modelle über die Anthropic Messages API'},
 {id:'foundry',label:'Azure Claude (Foundry)',hint:'Claude-Deployment in Microsoft Foundry, mit API-Schlüssel oder Entra ID'},
 {id:'google',label:'Google AI',hint:'Gemini-Modelle mit generateContent-Unterstützung'}
];
async function parseJson(response:Response){const text=await response.text();try{return JSON.parse(text)}catch{throw new Error('Der lokale API-Server hat keine gültige JSON-Antwort geliefert.')}}
function parseEnv(text:string):AiConfig{
 const values:Record<string,string>={};
 for(const raw of text.split(/\r?\n/)){const line=raw.trim().replace(/^export\s+/,'');if(!line||line.startsWith('#'))continue;const index=line.indexOf('=');if(index<1)continue;const key=line.slice(0,index).trim();let value=line.slice(index+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);values[key]=value}
 const configured=values.AI_PROVIDER?.toLowerCase();const provider:AiProvider=configured==='openai'||configured==='google'||configured==='azure'||configured==='anthropic'||configured==='foundry'?configured:values.FOUNDRY_ENDPOINT&&!configured?'foundry':values.OPENAI_API_KEY?'openai':values.ANTHROPIC_API_KEY?'anthropic':values.GOOGLE_AI_API_KEY||values.GEMINI_API_KEY?'google':'azure';
 if(provider==='azure')return{provider,apiKey:values.AZURE_OPENAI_API_KEY??'',endpoint:values.AZURE_OPENAI_ENDPOINT??'',model:values.AZURE_OPENAI_DEPLOYMENT??'gpt-5-mini'};
 if(provider==='openai')return{provider,apiKey:values.OPENAI_API_KEY??'',endpoint:'',model:values.OPENAI_MODEL??''};
 if(provider==='anthropic')return{provider,apiKey:values.ANTHROPIC_API_KEY??'',endpoint:values.ANTHROPIC_BASE_URL??'',model:values.ANTHROPIC_MODEL??'claude-opus-5-5'};
 if(provider==='foundry'){const entra=values.FOUNDRY_AUTH?.toLowerCase()==='entra';return{provider,apiKey:entra?'':values.FOUNDRY_API_KEY??'',endpoint:values.FOUNDRY_ENDPOINT??'',model:values.FOUNDRY_DEPLOYMENT??'',authMethod:entra?'entra':'apiKey'}}
 return{provider,apiKey:values.GOOGLE_AI_API_KEY??values.GEMINI_API_KEY??'',endpoint:'',model:values.GOOGLE_AI_MODEL??values.GEMINI_MODEL??''};
}

export default function AISettings({value,onSave,onClose,profile,stigLabel,firstRun,onSaveProfile}:{value:AiConfig;onSave:(next:AiConfig)=>void;onClose:()=>void;profile?:AnalysisProfile;stigLabel?:string;firstRun?:boolean;onSaveProfile?:(next:AnalysisProfile)=>void}){
 const[draft,setDraft]=useState(value);const[profileDraft,setProfileDraft]=useState<AnalysisProfile>(()=>profile??defaultProfile());
 const current=profileDraft[draft.provider];const patch=(change:Partial<ProviderProfile>)=>setProfileDraft(all=>({...all,[draft.provider]:{...all[draft.provider],...change}}));const template=templates.find(item=>item.id===current.templateId);const[models,setModels]=useState<string[]>([]);const[serverProviders,setServerProviders]=useState<Partial<Record<AiProvider,string>>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{setModels([]);setError('')},[draft.provider]);
 useEffect(()=>{void fetch('/api/health').then(response=>response.json()).then(json=>setServerProviders(Object.fromEntries((json.configuredProviders??[]).map((item:{provider:AiProvider;model:string})=>[item.provider,item.model])))).catch(()=>undefined)},[]);
 async function loadEnv(file?:File){if(!file)return;try{setDraft(parseEnv(await file.text()));setModels([]);setError('')}catch{setError('Die .env-Datei konnte nicht gelesen werden.')}}
 async function loadModels(){setBusy(true);setError('');try{const response=await fetch('/api/ai/models',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ai:draft})});const json=await parseJson(response);if(!response.ok)throw new Error(json.error);setModels(json.models??[]);if(!draft.model&&json.models?.length)setDraft(current=>({...current,model:json.models[0]}))}catch(reason){setError(reason instanceof Error?reason.message:'Modelle konnten nicht geladen werden.')}finally{setBusy(false)}}
 return <div className="settings-overlay"><section className="settings-modal">
  <div className="settings-head"><div><span>{firstRun?'NEUE STIG · EINSTELLUNGEN PRÜFEN':'KI-PROVIDER'}</span><h2>Analyse im Browser konfigurieren</h2></div><button onClick={onClose}><X/></button></div>
  <p className="settings-note"><KeyRound/> Zugangsdaten bleiben nur in dieser Browser-Sitzung gespeichert und werden ausschließlich über den lokalen Server an den gewählten Provider gesendet.</p>
  <label className="env-import"><input type="file" accept=".env,text/plain" onChange={event=>{void loadEnv(event.target.files?.[0]);event.currentTarget.value=''}}/><FileUp/><span><b>.env-Datei laden</b><small>Provider, Schlüssel, Endpoint und Modell lokal übernehmen</small></span></label>
  <div className="provider-grid">{providerNames.map(provider=><button key={provider.id} className={draft.provider===provider.id?'active':''} onClick={()=>setDraft(current=>({...current,provider:provider.id,apiKey:'',endpoint:provider.id==='azure'?current.endpoint:'',model:serverProviders[provider.id]??(provider.id==='azure'?'gpt-5-mini':provider.id==='anthropic'?'claude-opus-5-5':''),authMethod:provider.id==='foundry'?(current.authMethod??'apiKey'):undefined}))}><Cloud/><b>{provider.label}</b><small>{provider.hint}</small>{serverProviders[provider.id]!==undefined&&<em>Server-.env · {serverProviders[provider.id]||'Modell wählen'}</em>}</button>)}</div>
  <div className="settings-fields">{draft.provider==='azure'&&<label><span>Azure OpenAI Endpoint</span><input value={draft.endpoint} onChange={event=>setDraft({...draft,endpoint:event.target.value})} placeholder="https://…openai.azure.com"/></label>}{draft.provider==='foundry'&&<><label><span>Endpoint der Foundry-Ressource</span><input value={draft.endpoint} onChange={event=>setDraft({...draft,endpoint:event.target.value})} placeholder="https://RESSOURCE.services.ai.azure.com/anthropic"/></label><label><span>Deployment-Name</span><input value={draft.model} onChange={event=>setDraft({...draft,model:event.target.value})} placeholder="claude-haiku-4-5"/></label><div className="auth-method"><span>Authentifizierungsmethode</span><div className="scale">{([['apiKey','API-Schlüssel'],['entra','Microsoft Entra ID']]as const).map(([id,label])=><button type="button" key={id} className={(draft.authMethod??'apiKey')===id?'active':''} onClick={()=>setDraft({...draft,authMethod:id,apiKey:id==='entra'?'':draft.apiKey})}>{label}</button>)}</div>{draft.authMethod==='entra'&&<small>Lokal wird die Anmeldung von <code>az login</code> verwendet, in Azure die Managed Identity der Web App. Das Konto braucht die Rolle „Cognitive Services User“ auf der Foundry-Ressource.</small>}</div></>}{!(draft.provider==='foundry'&&draft.authMethod==='entra')&&<label><span>API-Key</span><input type="password" value={draft.apiKey} onChange={event=>setDraft({...draft,apiKey:event.target.value})} placeholder="Leer lassen, um die serverseitige .env zu verwenden"/></label>}{draft.provider==='foundry'?null:draft.provider==='anthropic'?<label><span>Modell</span><div className="model-row"><input list="claude-models" value={draft.model} onChange={event=>setDraft({...draft,model:event.target.value})} placeholder="claude-opus-5-5"/><datalist id="claude-models">{models.map(model=><option key={model} value={model}/>)}</datalist><button onClick={loadModels} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<RefreshCw/>} Modelle laden</button></div></label>:draft.provider==='azure'?<label><span>Deployment</span><input value={draft.model} onChange={event=>setDraft({...draft,model:event.target.value})} placeholder="gpt-5-mini"/></label>:<label><span>Modell</span><div className="model-row"><select value={draft.model} onChange={event=>setDraft({...draft,model:event.target.value})}><option value="">Modell auswählen…</option>{draft.model&&!models.includes(draft.model)&&<option>{draft.model}</option>}{models.map(model=><option key={model}>{model}</option>)}</select><button onClick={loadModels} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<RefreshCw/>} Modelle laden</button></div></label>}</div>
  {profile&&onSaveProfile&&<div className="profile-section"><div className="profile-head"><span>ANALYSE-VORGABEN · {providerNames.find(item=>item.id===draft.provider)?.label.toUpperCase()}</span><small>Gelten für {stigLabel||'die geladene STIG'} und werden im Browser gespeichert. Pro Provider getrennt einstellbar.</small></div>
   {firstRun&&<p className="settings-note profile-first">Für diese STIG sind noch keine Vorgaben hinterlegt. Prüfe Vorlage und Genauigkeit und speichere, damit sie beim nächsten Import automatisch gelten.</p>}
   <div className="template-grid">{templates.map(item=><button key={item.id} className={current.templateId===item.id?'active':''} onClick={()=>patch({templateId:item.id})}><b>{item.label}</b><small>{item.hint}</small></button>)}</div>
   {template?.text&&<p className="template-preview">{template.text}</p>}
   <label className="profile-free"><span>Eigene Vorgaben (Freitext)</span><textarea rows={4} maxLength={4000} value={current.instructions} onChange={event=>patch({instructions:event.target.value})} placeholder="Zum Beispiel: Zielsystem sind Windows-11-Clients in Intune. Keine Skripte, die Registry-Schlüssel direkt schreiben. Ergebnisse auf Deutsch."/></label>
   <div className="profile-scales"><div><span>Genauigkeit</span><div className="scale">{strictnessOptions.map(item=><button key={item.id} className={current.strictness===item.id?'active':''} onClick={()=>patch({strictness:item.id})} title={item.hint}>{item.label}</button>)}</div><small>{strictnessOptions.find(item=>item.id===current.strictness)?.hint}</small></div><div><span>Suchtiefe</span><div className="scale">{depthOptions.map(item=><button key={item.id} className={current.depth===item.id?'active':''} onClick={()=>patch({depth:item.id})} title={item.hint}>{item.label}</button>)}</div><small>{depthOptions.find(item=>item.id===current.depth)?.hint}{draft.provider!=='azure'&&draft.provider!=='anthropic'&&draft.provider!=='foundry'&&' · wirkt nur bei Azure OpenAI und Claude auf den Denkaufwand'}</small></div></div></div>}
  {error&&<p className="settings-error">{error}</p>}<footer><button onClick={onClose}>Abbrechen</button><button className="save" onClick={()=>{onSave(draft);onSaveProfile?.(profileDraft);onClose()}}>Für diese Sitzung speichern</button></footer>
 </section></div>;
}
