import{useEffect,useMemo,useState}from'react';
import{Search,ShieldCheck,Download,Sparkles,ChevronRight,X,SlidersHorizontal,FileJson,CheckCircle2,AlertTriangle,LoaderCircle,Clock3,FileDown,Package,Upload,ExternalLink,Info,GitCompare}from'lucide-react';
import type{AiConfig,CspMapping,RunRecord,StigDataset,StigRule}from'./types';
import ScriptExample from'./ScriptExample';
import RunHistory from'./RunHistory';
import{datasetKey,loadProfiles,loadRuns,mappingsFromRuns,profileFor,runsFor,saveProfiles,saveRuns}from'./runStore';
import PackagePage from'./PackagePage';
import{importStigZip}from'./stigParser';
import AISettings from'./AISettings';
import AboutDialog from'./AboutDialog';
import UserMenu from'./UserMenu';
const emptyDataset:StigDataset={benchmark:{title:'Keine STIG geladen',version:'',release:'',date:''},rules:[]};
const severityLabel={high:'Hoch',medium:'Mittel',low:'Niedrig'};
const targetLabel={intune_policy:'Intune-Richtlinie',entra_portal:'Entra-Portal/API',m365_portal:'Microsoft-365-Portal',configuration_management:'Konfigurationsmanagement',native_api:'Hersteller-API',os_native:'Betriebssystem-Konfiguration',application_configuration:'Anwendungskonfiguration',cloud_portal:'Cloud-Portal/API',local_script:'Lokales Skript',manual_only:'Manuell',not_applicable:'Nicht anwendbar'};
const defaultAi:AiConfig={provider:'azure',apiKey:'',endpoint:'',model:'gpt-5-mini'};
function normalizeMapping(value:Record<string,unknown>){return{...value,targetType:value.targetType??'manual_only',platform:value.platform??'Unbekannt',controlPlane:value.controlPlane??'Manuelle Prüfung',automationMethod:value.automationMethod??'Keine Automatisierung angegeben',apiEndpoint:value.apiEndpoint??'',permissions:Array.isArray(value.permissions)?value.permissions:[],artifacts:Array.isArray(value.artifacts)?value.artifacts:[],automationSteps:Array.isArray(value.automationSteps)?value.automationSteps:[],validationSteps:Array.isArray(value.validationSteps)?value.validationSteps:[],rollbackSteps:Array.isArray(value.rollbackSteps)?value.rollbackSteps:[],manualSteps:Array.isArray(value.manualSteps)?value.manualSteps:[],scriptLanguage:typeof value.scriptLanguage==='string'?value.scriptLanguage:'',scriptExample:typeof value.scriptExample==='string'?value.scriptExample:''}as unknown as CspMapping&{id:string}}
function download(name:string,value:unknown){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function App(){
 const[page,setPage]=useState<'stig'|'package'>('stig');
 const[ai,setAi]=useState<AiConfig>(()=>{try{return JSON.parse(sessionStorage.getItem('policy-studio-ai')??'null')??defaultAi}catch{return defaultAi}});const[settingsOpen,setSettingsOpen]=useState(false);const[aboutOpen,setAboutOpen]=useState(false);
 const[dataset,setDataset]=useState<StigDataset>(emptyDataset);const[importBusy,setImportBusy]=useState(false);const[importError,setImportError]=useState('');
 const[query,setQuery]=useState('');const[category,setCategory]=useState('Alle Kategorien');const[severity,setSeverity]=useState('all');const[selected,setSelected]=useState<Set<string>>(new Set());const[detail,setDetail]=useState<StigRule|null>(null);const[mappings,setMappings]=useState<Record<string,CspMapping>>({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
 const[monitorOpen,setMonitorOpen]=useState(false);const[analysisStatus,setAnalysisStatus]=useState<'idle'|'running'|'complete'|'error'>('idle');const[analysisStarted,setAnalysisStarted]=useState(0);const[elapsed,setElapsed]=useState(0);const[runs,setRuns]=useState<RunRecord[]>(loadRuns);const[viewId,setViewId]=useState('');const[profiles,setProfiles]=useState(loadProfiles);const[firstRun,setFirstRun]=useState(false);const[analysisError,setAnalysisError]=useState('');
 useEffect(()=>{if(analysisStatus!=='running')return;const timer=window.setInterval(()=>setElapsed(Math.floor((Date.now()-analysisStarted)/1000)),500);return()=>window.clearInterval(timer)},[analysisStatus,analysisStarted]);
 useEffect(()=>{if(sessionStorage.getItem('policy-studio-ai'))return;void fetch('/api/health').then(response=>response.json()).then(json=>{if(['azure','openai','google'].includes(json.configuredProvider))setAi({provider:json.configuredProvider,apiKey:'',endpoint:'',model:json.configuredModel||''})}).catch(()=>undefined)},[]);
 const categories=useMemo(()=>['Alle Kategorien',...Array.from(new Set(dataset.rules.map(r=>r.category))).sort()],[dataset]);
 const filtered=useMemo(()=>dataset.rules.filter(r=>(category==='Alle Kategorien'||r.category===category)&&(severity==='all'||r.severity===severity)&&(`${r.id} ${r.stigId} ${r.title} ${r.category}`.toLowerCase().includes(query.toLowerCase()))),[dataset,query,category,severity]);
 const dsKey=useMemo(()=>datasetKey(dataset),[dataset]);const dsRuns=useMemo(()=>runsFor(runs,dsKey),[runs,dsKey]);
 const selectedRules=dataset.rules.filter(r=>selected.has(r.id));const mappedCount=selectedRules.filter(r=>mappings[r.id]?.omaUri).length;
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 async function analyze(){if(!selectedRules.length)return;const started=Date.now();setBusy(true);setNotice('');setAnalysisError('');setAnalysisStarted(started);setElapsed(0);setAnalysisStatus('running');setMonitorOpen(true);try{const response=await fetch('/api/map-csp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rules:selectedRules.slice(0,30),ai,benchmark:dataset.benchmark,profile:profileFor(profiles,dsKey)[ai.provider]})});const text=await response.text();let json;try{json=JSON.parse(text)}catch{throw new Error('Der lokale API-Server lieferte keine gültige JSON-Antwort. Bitte „npm start“ neu starten.')}if(!response.ok)throw new Error(json.error);const results=((json.mappings??[])as Record<string,unknown>[]).map(normalizeMapping);const duration=Math.floor((Date.now()-started)/1000);const run:RunRecord={id:`${started}-${Math.random().toString(36).slice(2,8)}`,datasetKey:dsKey,createdAt:new Date().toISOString(),provider:ai.provider,model:ai.model,durationSec:duration,settings:(({templateId,strictness,depth})=>({templateId,strictness,depth}))(profileFor(profiles,dsKey)[ai.provider]),rules:selectedRules.slice(0,30).map(r=>({id:r.id,stigId:r.stigId,srgId:r.srgId,title:r.title})),results};const nextRuns=saveRuns([...runs,run]);setRuns(nextRuns);setViewId(run.id);setMappings(mappingsFromRuns(runsFor(nextRuns,dsKey)));setElapsed(duration);setAnalysisStatus('complete')}catch(e){const message=e instanceof Error?e.message:'Analyse fehlgeschlagen';setAnalysisError(message);setAnalysisStatus('error');setNotice(message)}finally{setBusy(false)}}
 function buildPolicy(items:Array<{rule:{id:string;stigId:string;srgId:string;title:string};m:CspMapping}>){const settings=items.flatMap(({rule,m})=>{if(!m.omaUri)return[];const graphType=m.dataType==='integer'?'#microsoft.graph.omaSettingInteger':m.dataType==='boolean'?'#microsoft.graph.omaSettingBoolean':m.dataType==='base64'?'#microsoft.graph.omaSettingBase64':'#microsoft.graph.omaSettingString';return[{"@odata.type":graphType,displayName:`${rule.stigId} — ${rule.title}`,description:`DISA ${rule.id} · ${rule.srgId}`,omaUri:m.omaUri,value:m.value}]});const label=`${dataset.benchmark.title} V${dataset.benchmark.version}`.trim();download(`${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-intune-csp.json`,{"@odata.type":"#microsoft.graph.windows10CustomConfiguration",displayName:label,description:`Ausgewählte Regeln aus ${label}. ${settings.length} validierte CSP-Einstellungen. Vor Produktiveinsatz testen.`,omaSettings:settings})}
 function exportPolicy(){buildPolicy(selectedRules.flatMap(rule=>mappings[rule.id]?[{rule,m:mappings[rule.id]}]:[]))}
 function exportRunPolicy(run:RunRecord){buildPolicy(run.results.flatMap(m=>{const rule=run.rules.find(r=>r.id===m.id);return rule?[{rule,m}]:[]}))}
 function exportReport(run:RunRecord){download(`stig-automatisierungsanalyse-${run.createdAt.slice(0,19).replace(/[:T]/g,'-')}.json`,{generatedAt:run.createdAt,provider:run.provider,model:run.model,summary:{analyzed:run.results.length,exportable:run.results.filter(m=>m.omaUri).length,notDirectlyMappable:run.results.filter(m=>!m.omaUri).length},results:run.results.map(m=>({rule:dataset.rules.find(r=>r.id===m.id)??run.rules.find(r=>r.id===m.id),mapping:m}))})}
 function deleteRun(id:string){const nextRuns=saveRuns(runs.filter(run=>run.id!==id));setRuns(nextRuns);setMappings(mappingsFromRuns(runsFor(nextRuns,dsKey)));if(viewId===id)setViewId('')}
 async function importZip(file?:File){if(!file)return;setImportBusy(true);setImportError('');try{const imported=await importStigZip(file);const next=imported[0].dataset;setDataset(next);setSelected(new Set());setMappings(mappingsFromRuns(runsFor(runs,datasetKey(next))));setViewId('');setAnalysisStatus('idle');setAnalysisError('');setMonitorOpen(false);setDetail(null);if(!profiles[datasetKey(next)]){setFirstRun(true);setSettingsOpen(true)}setCategory('Alle Kategorien');setSeverity('all');setQuery('');if(imported.length>1)setNotice(`${imported.length} Benchmarks gefunden; „${imported[0].dataset.benchmark.title}“ wurde geladen.`)}catch(reason){setImportError(reason instanceof Error?reason.message:'STIG-Import fehlgeschlagen')}finally{setImportBusy(false)}}
 const saveAi=(next:AiConfig)=>{setAi(next);sessionStorage.setItem('policy-studio-ai',JSON.stringify(next))};const providerName=ai.provider==='azure'?'Azure OpenAI':ai.provider==='openai'?'OpenAI':'Google AI';
 const header=<header><div className="brand"><span className="mark"><ShieldCheck/></span><div><strong>Policy Studio</strong><small>STIG → Automation</small></div></div><nav className="top-nav"><button className={page==='stig'?'active':''} onClick={()=>setPage('stig')}><ShieldCheck/>STIG Regeln</button><button className={page==='package'?'active':''} onClick={()=>setPage('package')}><Package/>Policy Package</button></nav><div className="release"><span className="live"/> {page==='stig'?(dataset.rules.length?`${dataset.benchmark.title} · V${dataset.benchmark.version}`:'STIG ZIP importieren'):'Policy Package ZIP importieren'} <b>{page==='stig'?dataset.benchmark.date:''}</b></div><button className="icon ai-config" title={`${providerName} · ${ai.model||'kein Modell'}`} onClick={()=>setSettingsOpen(true)}><SlidersHorizontal size={18}/><span>{providerName}</span></button><button className="icon" title="Über" aria-label="Über" onClick={()=>setAboutOpen(true)}><Info size={18}/></button><UserMenu/></header>;
 if(page==='package')return <div className="app">{header}<PackagePage ai={ai}/>{settingsOpen&&<AISettings value={ai} onSave={saveAi} onClose={()=>setSettingsOpen(false)}/>}{aboutOpen&&<AboutDialog onClose={()=>setAboutOpen(false)}/>}</div>;
 return <div className="app">{header}
 <main><section className="intro"><div><span className="eyebrow">SECURITY AUTOMATION WORKSPACE</span><h1>Aus Anforderungen werden<br/><em>automatisierbare Maßnahmen.</em></h1><p>{dataset.rules.length?`Durchsuche ${dataset.rules.length} Kontrollen aus ${dataset.benchmark.title}. Die KI erkennt Plattform und Zielsystem und entwickelt passende Automatisierungs-, Validierungs- und Rollback-Schritte.`:'Importiere ein originales DISA-STIG-ZIP. Der Viewer erkennt XCCDF-Benchmark, Produkt, Version und alle Regeln automatisch.'}</p><div className="import-actions"><label className="import-button"><Upload/>{importBusy?'ZIP wird verarbeitet…':'DISA STIG ZIP importieren'}<input type="file" accept=".zip,application/zip" disabled={importBusy} onChange={event=>{void importZip(event.target.files?.[0]);event.currentTarget.value=''}}/></label>{dsRuns.length>0&&<button className="import-button history-button" onClick={()=>setMonitorOpen(true)}><GitCompare/>Analyse-Historie ({dsRuns.length})</button>}<a href="https://www.cyber.mil/stigs/downloads/" target="_blank" rel="noreferrer"><ExternalLink/> STIG Downloadübersicht</a></div>{importError&&<p className="import-error"><AlertTriangle/>{importError}</p>}</div><div className="score"><div className="ring"><b>{selected.size}</b><span>gewählt</span></div><small>ANALYSE-FORTSCHRITT</small><strong>{mappedCount} CSP-exportbereit</strong></div></section>
 <section className="toolbar"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kontrollen, IDs oder Stichworte suchen…"/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><div className="segmented">{[['all','Alle'],['high','Hoch'],['medium','Mittel'],['low','Niedrig']].map(([v,l])=><button className={severity===v?'active':''} onClick={()=>setSeverity(v)} key={v}>{l}</button>)}</div></section>
 <div className="layout"><aside><div className="side-title"><span>KATEGORIEN</span><small>{dataset.rules.length} Regeln</small></div>{categories.map(c=>{const n=c==='Alle Kategorien'?dataset.rules.length:dataset.rules.filter(r=>r.category===c).length;return <button key={c} className={category===c?'current':''} onClick={()=>setCategory(c)}><span>{c}</span><b>{n}</b></button>})}{dataset.rules.length>0&&<div className="source"><FileJson size={19}/><div><b>V{dataset.benchmark.version} · {dataset.benchmark.release||'XCCDF'}</b><small>{dataset.benchmark.date||'Importierte Benchmark'}</small></div></div>}</aside>
 <section className="content"><div className="list-head"><div><h2>{category}</h2><p>{filtered.length} Kontrollen · nach Schweregrad sortiert</p></div><label className="select-all"><input type="checkbox" checked={filtered.length>0&&filtered.every(r=>selected.has(r.id))} onChange={e=>setSelected(s=>{const n=new Set(s);filtered.forEach(r=>e.target.checked?n.add(r.id):n.delete(r.id));return n})}/> Alle sichtbaren</label></div>
 <div className="cards">{filtered.map(r=><article key={r.id} className={selected.has(r.id)?'selected':''}><input className="check" type="checkbox" checked={selected.has(r.id)} onChange={()=>toggle(r.id)}/><div className="card-main" onClick={()=>setDetail(r)}><div className="meta"><span className={`sev ${r.severity}`}>{severityLabel[r.severity]}</span><code>{r.stigId}</code><span>{r.id}</span>{r.registry&&<span className="registry">Registry</span>}</div><h3>{r.title}</h3><p>{r.fix}</p><div className="tags"><span>{r.category}</span>{r.cci.slice(0,2).map(c=><span key={c}>{c}</span>)}</div></div><button className="arrow" onClick={()=>setDetail(r)}><ChevronRight/></button></article>)}</div></section></div></main>
 {selected.size>0&&<div className="actionbar"><div><b>{selected.size}</b><span>Kontrollen ausgewählt</span><small>{mappedCount} exportbereit</small></div>{(analysisStatus!=='idle'||dsRuns.length>0)&&!busy&&<button className="report" onClick={()=>setMonitorOpen(true)}><FileJson/> Ergebnis anzeigen</button>}<button className="ai" onClick={analyze} disabled={busy||selected.size>30}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{selected.size>30?'Max. 30 pro Analyse':`Mit ${providerName} prüfen`}</button><button className="export" onClick={exportPolicy} disabled={!mappedCount}><Download/> Intune JSON exportieren</button></div>}
 {notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}<X size={16}/></div>}
 {monitorOpen&&<div className="monitor-overlay"><section className={`monitor${analysisStatus==='running'||analysisStatus==='error'?'':' wide'}`}><div className="monitor-head"><div className={`monitor-icon ${analysisStatus}`}>{analysisStatus==='running'?<LoaderCircle className="spin"/>:analysisStatus==='complete'?<CheckCircle2/>:<AlertTriangle/>}</div><div><span>{providerName.toUpperCase()} · {(ai.model||'MODELL').toUpperCase()}</span><h2>{analysisStatus==='running'?'Umsetzung und Automatisierung werden analysiert':analysisStatus==='complete'?'Analyse abgeschlossen':analysisStatus==='idle'?'Analyse-Historie':'Analyse fehlgeschlagen'}</h2></div>{!busy&&<button onClick={()=>setMonitorOpen(false)}><X/></button>}</div><div hidden={analysisStatus==='complete'||analysisStatus==='idle'}><div className="monitor-progress"><i className={analysisStatus==='running'?'moving':''} style={{width:analysisStatus==='complete'?'100%':analysisStatus==='error'?'100%':'68%'}}/><div><span>{analysisStatus==='running'?'Modell prüft Intune, Portale und APIs…':analysisStatus==='complete'?'Ergebnisse validiert':'Verarbeitung abgebrochen'}</span><b><Clock3/> {elapsed}s</b></div></div><div className="monitor-steps">{[`Anfrage sicher an ${providerName} übertragen`,'Zielsystem klassifizieren','API und Berechtigungen prüfen','Automatisierungsplan erstellen'].map((label,i)=>{const done=analysisStatus==='complete'||(analysisStatus==='running'&&i<2);const active=analysisStatus==='running'&&i===2;return <div className={done?'done':active?'active':''} key={label}>{done?<CheckCircle2/>:active?<LoaderCircle className="spin"/>:<span>{i+1}</span>}<p>{label}</p></div>})}</div></div>{analysisStatus==='running'&&<div className="monitor-wait"><Sparkles/><div><b>Analyse läuft</b><p>Das Fenster aktualisiert sich automatisch. Je nach Auslastung des Anbieters kann die Verarbeitung einige Sekunden dauern.</p></div></div>}{analysisStatus==='error'&&<div className="monitor-error"><AlertTriangle/><div><b>{providerName}-Anfrage fehlgeschlagen</b><p>{analysisError}</p></div></div>}{(analysisStatus==='complete'||analysisStatus==='idle')&&dsRuns.length>0&&<RunHistory runs={dsRuns} activeId={viewId||dsRuns[0].id} onSelect={setViewId} onDelete={deleteRun} onExportReport={exportReport} onExportPolicy={exportRunPolicy}/>}</section></div>}
 {detail&&<div className="overlay" onClick={()=>setDetail(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}><X/></button><span className={`sev ${detail.severity}`}>{severityLabel[detail.severity]}</span><code>{detail.stigId} · {detail.id}</code><h2>{detail.title}</h2><h4>Anforderung</h4><p>{detail.fix}</p>{detail.registry&&<><h4>Registry-Nachweis</h4><div className="regbox"><span>{detail.registry.hive}</span><b>{detail.registry.path}</b><code>{detail.registry.name} · {detail.registry.type} · {detail.registry.value}</code></div></>}<h4>Umsetzung</h4>{mappings[detail.id]?<><div className="mapping"><CheckCircle2/><div><strong>{targetLabel[mappings[detail.id].targetType]}</strong><code>{mappings[detail.id].omaUri||mappings[detail.id].apiEndpoint||mappings[detail.id].controlPlane}</code><p>{mappings[detail.id].rationale}</p></div></div><h4>Automatisierung</h4><div className="automation-plan"><b>{mappings[detail.id].automationMethod}</b><p><strong>Plattform:</strong> {mappings[detail.id].platform} · <strong>Steuerung:</strong> {mappings[detail.id].controlPlane}</p>{mappings[detail.id].permissions.length>0&&<p><strong>Berechtigungen:</strong> {mappings[detail.id].permissions.join(', ')}</p>}{mappings[detail.id].artifacts.length>0&&<p><strong>Artefakte:</strong> {mappings[detail.id].artifacts.join(', ')}</p>}<small>Umsetzung</small><ol>{mappings[detail.id].automationSteps.map(step=><li key={step}>{step}</li>)}</ol><small>Validierung</small><ol>{mappings[detail.id].validationSteps.map(step=><li key={step}>{step}</li>)}</ol><small>Rollback</small><ol>{mappings[detail.id].rollbackSteps.map(step=><li key={step}>{step}</li>)}</ol><ScriptExample language={mappings[detail.id].scriptLanguage} code={mappings[detail.id].scriptExample}/>{mappings[detail.id].manualSteps.length>0&&<><small>Manuelle Alternative</small><ol>{mappings[detail.id].manualSteps.map(step=><li key={step}>{step}</li>)}</ol></>}</div></>:<div className="mapping pending"><AlertTriangle/><p>Noch nicht geprüft. Regel auswählen und Analyse mit {providerName} starten.</p></div>}<h4>Prüfung</h4><p className="pre">{detail.check}</p></div></div>}
 {settingsOpen&&<AISettings key={`${dsKey}-${firstRun}`} value={ai} onSave={saveAi} onClose={()=>{setSettingsOpen(false);setFirstRun(false)}} profile={dataset.rules.length?profileFor(profiles,dsKey):undefined} stigLabel={`${dataset.benchmark.title} V${dataset.benchmark.version}`} firstRun={firstRun} onSaveProfile={next=>setProfiles(saveProfiles({...profiles,[dsKey]:next}))}/>}{aboutOpen&&<AboutDialog onClose={()=>setAboutOpen(false)}/>}</div>}
export default App;
