import{strFromU8,unzipSync}from'fflate';
import type{PackageDataset,PackagePolicy}from'./types';

export interface ImportedPackagePolicy extends PackagePolicy{payload:Record<string,unknown>}
export interface ImportedPackageDataset extends Omit<PackageDataset,'policies'>{policies:ImportedPackagePolicy[]}
function decode(value:Uint8Array){if(value[0]===0xff&&value[1]===0xfe)return new TextDecoder('utf-16le').decode(value.subarray(2));if(value[0]===0xfe&&value[1]===0xff)return new TextDecoder('utf-16be').decode(value.subarray(2));return strFromU8(value).replace(/^\uFEFF/,'')}
function product(name:string){for(const[label,pattern]of[['Windows 11',/Windows 11/i],['Windows 10',/Windows 10/i],['Microsoft Defender',/Defender/i],['Microsoft Edge',/Edge/i],['Google Chrome',/Chrome/i],['Microsoft 365 Apps',/M365|Office/i],['Adobe Acrobat',/Adobe Acrobat/i],['Internet Explorer',/Internet Explorer/i],['Mozilla Firefox',/Firefox/i],['OneDrive',/OneDrive/i],['Windows',/Windows|USB|\.NET/i]]as const)if(pattern.test(name))return label;return'Weitere'}
function platform(value:unknown,name:string){const raw=String(value??'').toLowerCase();if(raw.includes('mac')||/macOS/i.test(name))return'macOS';if(raw.includes('android')||/Android/i.test(name))return'Android';return'Windows'}
function version(name:string){const match=name.match(/\bv\d+r\d+\b/i)??name.match(/\b(\d+)vr(\d+)\b/i);return match?match[0].replace(/^(\d+)vr(\d+)$/i,'v$1r$2').toLowerCase():'Ohne Versionsangabe'}
function countSettings(json:Record<string,unknown>){if(typeof json.settingCount==='number')return json.settingCount;for(const key of['settings','omaSettings','definitionValues','customSettings'])if(Array.isArray(json[key]))return json[key].length;return undefined}
function basename(path:string){return path.split('/').pop()?.replace(/\.json$/i,'')??path}
function collect(zip:Uint8Array,depth=0,prefix=''):Array<{name:string;value:Uint8Array}>{if(depth>2)throw new Error('Das ZIP ist zu tief verschachtelt.');const entries=Object.entries(unzipSync(zip));if(entries.length>1500)throw new Error('Das ZIP enthält zu viele Dateien.');const total=entries.reduce((sum,[,value])=>sum+value.length,0);if(total>150*1024*1024)throw new Error('Der entpackte Inhalt überschreitet 150 MB.');return entries.flatMap(([name,value])=>/\.zip$/i.test(name)?collect(value,depth+1,`${prefix}${name}!/`):[{name:`${prefix}${name}`,value}])}
function releaseFrom(name:string){const match=name.replace(/_/g,' ').match(/(January|February|March|April|May|June|July|August|September|October|November|December)\s+20\d{2}/i);return match?match[0].replace(/^./,letter=>letter.toUpperCase()):'Importiertes Package'}

export async function importPolicyPackage(file:File):Promise<ImportedPackageDataset>{
 if(file.size>100*1024*1024)throw new Error('ZIP-Dateien dürfen maximal 100 MB groß sein.');const entries=collect(new Uint8Array(await file.arrayBuffer()));const policies:ImportedPackagePolicy[]=[];
 for(const entry of entries){const normalized=entry.name.replace(/\\/g,'/');const parts=normalized.split('/');const root=parts.findIndex(part=>part.toLowerCase()==='intune policies');if(root<0||parts.length<root+3||!/\.json$/i.test(normalized))continue;let payload:Record<string,unknown>;try{payload=JSON.parse(decode(entry.value))as Record<string,unknown>}catch{continue}const category=parts[root+1];const name=String(payload.name??payload.displayName??basename(normalized));const id=parts.slice(root).join('/');policies.push({id,name,version:version(name),category,product:product(name),platform:platform(payload.platforms,name),description:String(payload.description??''),settings:countSettings(payload),technology:String(payload.technologies??payload['@odata.type']??category),sourceFile:normalized,fileSize:entry.value.length,payload});
 }
 if(!policies.length)throw new Error('Keine importierbaren Intune-Policy-JSONs unter „Intune Policies“ gefunden.');policies.sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));const release=releaseFrom(file.name+entries.map(entry=>entry.name).join(' '));return{package:{name:'DISA STIG Intune Policy Package',release,scope:'Windows und ergänzende Anwendungsprofile',warning:'Alle Richtlinien müssen vor dem Produktiveinsatz in einer repräsentativen Testumgebung geprüft werden.',guidance:'Importierte Original-Policies werden ausschließlich lokal im Browser verarbeitet.',knownIssues:[]},policies};
}
