import{useMemo,useState}from'react';
import{AlertTriangle,Box,CheckCircle2,ChevronRight,Download,ExternalLink,FileJson,Layers3,LoaderCircle,PackageCheck,Search,Sparkles,Upload,X}from'lucide-react';
import type{AiConfig,PackageAssessment,PackagePolicy}from'./types';
import ScriptExample from'./ScriptExample';
import{importPolicyPackage,type ImportedPackageDataset}from'./packageParser';
function save(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function formatSize(bytes:number){return bytes<1024?`${bytes} B`:`${Math.round(bytes/1024)} KB`}
async function jsonResponse(response:Response){const text=await response.text();try{return JSON.parse(text)}catch{throw new Error(response.ok?'Der Server hat keine gültigen JSON-Daten geliefert.':'Der API-Server ist nicht erreichbar oder der Endpunkt fehlt. Bitte die Anwendung mit „npm start“ ausführen.')}}
const targetLabel={intune_policy:'Intune-Richtlinie',entra_portal:'Entra-Portal/API',m365_portal:'Microsoft-365-Portal',configuration_management:'Konfigurationsmanagement',native_api:'Hersteller-API',os_native:'Betriebssystem-Konfiguration',application_configuration:'Anwendungskonfiguration',cloud_portal:'Cloud-Portal/API',local_script:'Lokales Skript',manual_only:'Manuell',not_applicable:'Nicht anwendbar'};
function normalizeAssessment(value:Record<string,unknown>){return{...value,targetType:value.targetType??'manual_only',platform:value.platform??'Unbekannt',controlPlane:value.controlPlane??'Manuelle Prüfung',automationMethod:value.automationMethod??'Keine Automatisierung angegeben',apiEndpoint:value.apiEndpoint??'',permissions:Array.isArray(value.permissions)?value.permissions:[],artifacts:Array.isArray(value.artifacts)?value.artifacts:[],automationSteps:Array.isArray(value.automationSteps)?value.automationSteps:[],validationSteps:Array.isArray(value.validationSteps)?value.validationSteps:[],rollbackSteps:Array.isArray(value.rollbackSteps)?value.rollbackSteps:[],manualSteps:Array.isArray(value.manualSteps)?value.manualSteps:[],scriptLanguage:typeof value.scriptLanguage==='string'?value.scriptLanguage:'',scriptExample:typeof value.scriptExample==='string'?value.scriptExample:'',dependencies:Array.isArray(value.dependencies)?value.dependencies:[],risks:Array.isArray(value.risks)?value.risks:[]}as unknown as PackageAssessment}

export default function PackagePage({ai}:{ai:AiConfig}){
 const[data,setData]=useState<ImportedPackageDataset|null>(null);const[query,setQuery]=useState('');const[category,setCategory]=useState('Alle Typen');const[platform,setPlatform]=useState('Alle');const[version,setVersion]=useState('Alle Versionen');const[selected,setSelected]=useState<Set<string>>(new Set());const[detail,setDetail]=useState<PackagePolicy|null>(null);const[assessments,setAssessments]=useState<Record<string,PackageAssessment>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const policies=data?.policies??[];const categories=useMemo(()=>['Alle Typen',...Array.from(new Set(policies.map(p=>p.category))).sort()],[policies]);
 const versions=useMemo(()=>['Alle Versionen',...Array.from(new Set(policies.map(p=>p.version))).sort()],[policies]);
 const filtered=useMemo(()=>policies.filter(p=>(category==='Alle Typen'||p.category===category)&&(platform==='Alle'||p.platform===platform)&&(version==='Alle Versionen'||p.version===version)&&`${p.name} ${p.version} ${p.product} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase())),[policies,query,category,platform,version]);
 const chosen=policies.filter(p=>selected.has(p.id));
 function toggle(id:string){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
 async function analyze(){if(!chosen.length)return;setBusy(true);setError('');try{const response=await fetch('/api/package/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({policies:chosen.slice(0,20),ai})});const json=await jsonResponse(response);if(!response.ok)throw new Error(json.error);const results=((json.assessments??[])as Record<string,unknown>[]).map(normalizeAssessment);setAssessments(Object.fromEntries(results.map(item=>[item.id,item])))}catch(reason){setError(reason instanceof Error?reason.message:'Analyse fehlgeschlagen')}finally{setBusy(false)}}
 function exportPackage(){if(!data)return;save('disa-stig-intune-policy-auswahl.json',{schemaVersion:'1.0',displayName:`Auswahl aus ${data.package.name} · ${data.package.release}`,generatedAt:new Date().toISOString(),warning:data.package.warning,policies:chosen.map(policy=>policy.payload)})}
 async function importZip(file?:File){if(!file)return;setBusy(true);setError('');try{setData(await importPolicyPackage(file));setSelected(new Set());setAssessments({});setDetail(null);setCategory('Alle Typen');setPlatform('Alle');setVersion('Alle Versionen');setQuery('')}catch(reason){setError(reason instanceof Error?reason.message:'Package-Import fehlgeschlagen')}finally{setBusy(false)}}
 return <><main className="package-main"><section className="intro package-intro"><div><span className="eyebrow">OFFICIAL POLICY PACKAGE WORKSPACE</span><h1>Vorhandene Policies zum<br/><em>Importpaket zusammenstellen.</em></h1><p>{data?`${data.package.scope}. Durchsuche die importierten DISA-Exporte, prüfe Abhängigkeiten mit KI und bündele nur die benötigten Konfigurationen.`:'Importiere ein originales DISA Intune Policy Package als ZIP. Profiltyp, Produkt, Plattform und Version werden automatisch erkannt.'}</p><div className="import-actions"><label className="import-button"><Upload/>{busy?'ZIP wird verarbeitet…':'Intune Policy ZIP importieren'}<input type="file" accept=".zip,application/zip" disabled={busy} onChange={event=>{void importZip(event.target.files?.[0]);event.currentTarget.value=''}}/></label><a href="https://www.cyber.mil/stigs/gpo" target="_blank" rel="noreferrer"><ExternalLink/> Policy Packages herunterladen</a></div></div><div className="score"><div className="ring package-ring"><b>{selected.size}</b><span>gewählt</span></div><small>PAKET-FORTSCHRITT</small><strong>{Object.keys(assessments).filter(id=>selected.has(id)).length} KI-geprüft</strong></div></section>
 <div className="package-warning"><AlertTriangle/><div><b>Vor dem Produktiveinsatz testen</b><p>{data?.package.warning??'Importierte Richtlinien müssen vor dem Produktiveinsatz in einer repräsentativen Testumgebung geprüft werden.'}</p></div></div>
 <section className="toolbar"><label className="search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Policies, Produkte, Versionen oder Profiltypen suchen…"/></label><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select><select value={version} onChange={event=>setVersion(event.target.value)}>{versions.map(item=><option key={item}>{item}</option>)}</select><div className="segmented">{['Alle','Windows','macOS','Android'].map(item=><button key={item} className={platform===item?'active':''} onClick={()=>setPlatform(item)}>{item}</button>)}</div></section>
 <div className="layout"><aside><div className="side-title"><span>PROFILTYPEN</span><small>{policies.length} Policies</small></div>{categories.map(item=>{const count=item==='Alle Typen'?policies.length:policies.filter(p=>p.category===item).length;return <button key={item} className={category===item?'current':''} onClick={()=>setCategory(item)}><span>{item}</span><b>{count}</b></button>})}{data&&<div className="source"><PackageCheck size={19}/><div><b>{data.package.release}</b><small>DISA Intune Package</small></div></div>}</aside>
 <section className="content"><div className="list-head"><div><h2>{category}</h2><p>{filtered.length} Policies · Originalexporte aus dem Paket</p></div><label className="select-all"><input type="checkbox" checked={filtered.length>0&&filtered.every(p=>selected.has(p.id))} onChange={event=>setSelected(current=>{const next=new Set(current);filtered.forEach(p=>event.target.checked?next.add(p.id):next.delete(p.id));return next})}/> Alle sichtbaren</label></div>
 <div className="cards">{filtered.map(policy=><article key={policy.id} className={selected.has(policy.id)?'selected':''}><input className="check" type="checkbox" checked={selected.has(policy.id)} onChange={()=>toggle(policy.id)}/><div className="card-main" onClick={()=>setDetail(policy)}><div className="meta"><span className="sev package-type">{policy.platform}</span><strong className="version-badge">{policy.version}</strong><code>{policy.category}</code>{typeof policy.settings==='number'&&<span>{policy.settings} Einstellungen</span>}{assessments[policy.id]&&<span className="registry">KI geprüft</span>}</div><h3>{policy.name}</h3><p>{assessments[policy.id]?.purpose||policy.description||`Importierbares ${policy.category}-Profil für ${policy.product}.`}</p><div className="tags"><span>{policy.product}</span><span>{formatSize(policy.fileSize)}</span></div></div><button className="arrow" onClick={()=>setDetail(policy)}><ChevronRight/></button></article>)}</div></section></div></main>
 {selected.size>0&&<div className="actionbar"><div><b>{selected.size}</b><span>Policies ausgewählt</span><small>{Object.keys(assessments).filter(id=>selected.has(id)).length} erklärt</small></div><button className="ai" onClick={analyze} disabled={busy||selected.size>20}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{selected.size>20?'Max. 20 pro Analyse':'Auswahl mit KI erklären'}</button><button className="export" onClick={exportPackage} disabled={busy}><Download/> Intune-Paket bauen</button></div>}
 {error&&<div className="toast" onClick={()=>setError('')}><AlertTriangle size={16}/>{error}<X size={16}/></div>}
 {detail&&<div className="overlay" onClick={()=>setDetail(null)}><div className="drawer" onClick={event=>event.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}><X/></button><span className="sev package-type">{detail.platform}</span><strong className="version-badge drawer-version">{detail.version}</strong><code>{detail.category}</code><h2>{detail.name}</h2><h4>Zweck und Einordnung</h4><p>{assessments[detail.id]?.purpose||detail.description||`Dieses Profil konfiguriert ${detail.product} über den Intune-Profiltyp „${detail.category}“.`}</p><div className="package-facts"><div><Layers3/><span>Profiltyp</span><b>{detail.category}</b></div><div><FileJson/><span>Umfang</span><b>{detail.settings??'—'} Einstellungen</b></div><div><Box/><span>Version</span><b>{detail.version}</b></div></div>{assessments[detail.id]?<><h4>KI-Empfehlung</h4><div className="mapping"><CheckCircle2/><div><strong>{targetLabel[assessments[detail.id].targetType]}</strong><p>{assessments[detail.id].recommendation}</p><small>Konfidenz: {assessments[detail.id].confidence}</small></div></div><h4>Automatisierung</h4><div className="automation-plan"><b>{assessments[detail.id].automationMethod}</b><p><strong>Plattform:</strong> {assessments[detail.id].platform} · <strong>Steuerung:</strong> {assessments[detail.id].controlPlane}</p>{assessments[detail.id].apiEndpoint&&<code>{assessments[detail.id].apiEndpoint}</code>}{assessments[detail.id].permissions.length>0&&<p><strong>Berechtigungen:</strong> {assessments[detail.id].permissions.join(', ')}</p>}{assessments[detail.id].artifacts.length>0&&<p><strong>Artefakte:</strong> {assessments[detail.id].artifacts.join(', ')}</p>}<small>Umsetzung</small><ol>{assessments[detail.id].automationSteps.map(item=><li key={item}>{item}</li>)}</ol><small>Validierung</small><ol>{assessments[detail.id].validationSteps.map(item=><li key={item}>{item}</li>)}</ol><small>Rollback</small><ol>{assessments[detail.id].rollbackSteps.map(item=><li key={item}>{item}</li>)}</ol><ScriptExample language={assessments[detail.id].scriptLanguage} code={assessments[detail.id].scriptExample}/>{assessments[detail.id].manualSteps.length>0&&<><small>Manuelle Alternative</small><ol>{assessments[detail.id].manualSteps.map(item=><li key={item}>{item}</li>)}</ol></>}</div><h4>Abhängigkeiten</h4><ul className="detail-list">{assessments[detail.id].dependencies.map(item=><li key={item}>{item}</li>)}</ul><h4>Risiken und Prüfbedarf</h4><ul className="detail-list warning-list">{assessments[detail.id].risks.map(item=><li key={item}>{item}</li>)}</ul></>:<><h4>KI-Erklärung</h4><div className="mapping pending"><Sparkles/><p>Policy auswählen und „Auswahl mit KI erklären“ starten, um Zielsystem, Zweck, Automatisierung, Validierung, Rollback, Abhängigkeiten und Risiken zu erhalten.</p></div></>}<h4>Quelldatei</h4><p className="pre source-path">{detail.sourceFile}</p></div></div>}
 </>;
}
