import{XMLParser}from'fast-xml-parser';
import{strFromU8,unzipSync}from'fflate';
import type{StigDataset,StigRule}from'./types';

const text=(value:unknown):string=>typeof value==='string'?value.trim():(value&&typeof value==='object'&&'#text'in value?String((value as Record<string,unknown>)['#text']).trim():'');
const arr=<T>(value:T|T[]|undefined):T[]=>value===undefined?[]:Array.isArray(value)?value:[value];
const clean=(value:unknown)=>text(value).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function category(title:string,fix:string){const value=`${title} ${fix}`.toLowerCase();const groups:[string,string[]][]=[['Identität & Zugriff',['password','account','credential','logon','authentication','identity','entra','pam','sudo']],['Kryptografie & Zertifikate',['bitlocker','encryption','encrypt','crypto','cipher','certificate','fve','tpm','fips']],['Überwachung & Protokollierung',['audit','event log','logging','journal','syslog']],['Netzwerk & Firewall',['firewall','network','smb','winrm','remote desktop','rdp','ipv6','ssh']],['Dateisystem & Berechtigungen',['file permission','ownership','mount','filesystem','directory','selinux']],['Dienste & Prozesse',['service','daemon','process','systemd']],['Pakete & Updates',['package','patch','update','repository','dnf','rpm']],['Anwendungen & Laufzeit',['application','browser','edge','applocker','installer','runtime']],['Geräte & Datenträger',['removable','device','drive','volume','autoplay','autorun','usb']],['Systemhärtung',['registry','group policy','security option','kernel','sysctl','boot','system']]];return groups.find(([,words])=>words.some(word=>value.includes(word)))?.[0]??'Sonstige Anforderungen'}
function registry(check:string){const pick=(label:string)=>check.match(new RegExp(`${label}:\\s*([^\\n\\r]+)`,'i'))?.[1]?.trim()??'';const hive=pick('Registry Hive');return hive?{hive,path:pick('Registry Path'),name:pick('Value Name'),type:pick('Type'),value:pick('Value')}:undefined}

export function parseXccdf(xml:string):StigDataset{
 const parsed=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',parseTagValue:false,trimValues:true,removeNSPrefix:true}).parse(xml) as Record<string,unknown>;
 const benchmark=(parsed.Benchmark??parsed.benchmark)as Record<string,unknown>|undefined;if(!benchmark)throw new Error('Keine gültige XCCDF-Benchmark gefunden.');
 const rules:StigRule[]=arr<Record<string,unknown>>(benchmark.Group as Record<string,unknown>|Record<string,unknown>[]).flatMap(group=>{const rule=group.Rule as Record<string,unknown>|undefined;if(!rule)return[];const check=text((rule.check as Record<string,unknown>|undefined)?.['check-content']);const fix=text(rule.fixtext);const title=text(rule.title);return[{id:String(group['@_id']??''),ruleId:String(rule['@_id']??''),stigId:text(rule.version),srgId:text(group.title),title,severity:String(rule['@_severity']??'medium')as StigRule['severity'],category:category(title,fix),cci:arr(rule.ident).map(text),discussion:clean(rule.description),check,fix,registry:registry(check)}]});
 if(!rules.length)throw new Error('Die XCCDF-Datei enthält keine lesbaren STIG-Regeln.');const releaseNodes=arr<Record<string,unknown>>(benchmark['plain-text']as Record<string,unknown>|Record<string,unknown>[]);const release=text(releaseNodes.find(item=>item['@_id']==='release-info'));const major=text(benchmark.version);const revision=release.match(/Release:\s*(\d+)/i)?.[1];
 return{benchmark:{title:text(benchmark.title),version:revision?`${major}R${revision}`:major,release,date:String((benchmark.status as Record<string,unknown>|undefined)?.['@_date']??'')},rules};
}

function collectXml(zip:Uint8Array,depth=0):Array<{name:string;xml:string}>{if(depth>2)throw new Error('Das ZIP ist zu tief verschachtelt.');const entries=unzipSync(zip);const files=Object.entries(entries);if(files.length>500)throw new Error('Das ZIP enthält zu viele Dateien.');const total=files.reduce((sum,[,value])=>sum+value.length,0);if(total>100*1024*1024)throw new Error('Der entpackte Inhalt überschreitet 100 MB.');return files.flatMap(([name,value])=>/\.zip$/i.test(name)?collectXml(value,depth+1):/(manual[-_]xccdf|xccdf).*\.xml$/i.test(name)||/\.xml$/i.test(name)&&strFromU8(value.subarray(0,5000)).includes('Benchmark')?[{name,xml:strFromU8(value)}]:[])}
export async function importStigZip(file:File){if(file.size>50*1024*1024)throw new Error('ZIP-Dateien dürfen maximal 50 MB groß sein.');const candidates=collectXml(new Uint8Array(await file.arrayBuffer()));if(!candidates.length)throw new Error('Keine XCCDF-XML-Datei im ZIP gefunden.');const results=[];for(const candidate of candidates)try{results.push({name:candidate.name,dataset:parseXccdf(candidate.xml)})}catch{/* Andere XML-Dateien im Paket überspringen. */}if(!results.length)throw new Error('Keine unterstützte XCCDF-Benchmark im ZIP gefunden.');return results}
